eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: service-config
  cloud:
    config:
      server:
        git:  #git地址
          uri: https://github.com/891760188/spring-cloud-explore/
          searchPaths: configFileDir
          username:
          password:
      label: master

server:
  port: 8888



